shamefullyHoist: true

allowBuilds:
  "@parcel/watcher": false
  "@prisma/client": true
  "@prisma/engines": true
  better-sqlite3: false
  esbuild: false
  prisma: true
  sharp: false
  unrs-resolver: false
  vue-demi: false

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  # Nuxt
  - "@nuxt/*"
  - "@nuxtjs/*"
  - nuxt
  - nuxt-*
  # Vercel
  - "@vercel/*"
  - "@ai-sdk/*"
  - ai
