shamefullyHoist: true

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
  better-sqlite3: false
  sharp: false
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  # Nuxt
  - '@nuxt/*'
  - '@nuxtjs/*'
  - 'nuxt'
  - 'nuxt-*'
  # Vercel
  - '@vercel/*'
  - '@ai-sdk/*'
  - 'ai'
