export const SEASON = 2026

export const seedTeams = [
  { name: 'McLaren', color: '#FF8000' },
  { name: 'Ferrari', color: '#E8002D' },
  { name: 'Red Bull Racing', color: '#3671C6' },
  { name: 'Mercedes', color: '#27F4D2' },
  { name: 'Aston Martin', color: '#229971' },
  { name: 'Alpine', color: '#FF87BC' },
  { name: 'Haas', color: '#B6BABD' },
  { name: 'Racing Bulls', color: '#6692FF' },
  { name: 'Williams', color: '#64C4FF' },
  { name: 'Audi', color: '#C0C0C0' },
  { name: 'Cadillac', color: '#1E1E1E' },
]

export const seedDrivers: { firstName: string, lastName: string, number: number, team: string }[] = [
  { firstName: 'Lando', lastName: 'Norris', number: 1, team: 'McLaren' },
  { firstName: 'Oscar', lastName: 'Piastri', number: 81, team: 'McLaren' },
  { firstName: 'Charles', lastName: 'Leclerc', number: 16, team: 'Ferrari' },
  { firstName: 'Lewis', lastName: 'Hamilton', number: 44, team: 'Ferrari' },
  { firstName: 'Max', lastName: 'Verstappen', number: 3, team: 'Red Bull Racing' },
  { firstName: 'Isack', lastName: 'Hadjar', number: 6, team: 'Red Bull Racing' },
  { firstName: 'George', lastName: 'Russell', number: 63, team: 'Mercedes' },
  { firstName: 'Kimi', lastName: 'Antonelli', number: 12, team: 'Mercedes' },
  { firstName: 'Fernando', lastName: 'Alonso', number: 14, team: 'Aston Martin' },
  { firstName: 'Lance', lastName: 'Stroll', number: 18, team: 'Aston Martin' },
  { firstName: 'Pierre', lastName: 'Gasly', number: 10, team: 'Alpine' },
  { firstName: 'Franco', lastName: 'Colapinto', number: 43, team: 'Alpine' },
  { firstName: 'Esteban', lastName: 'Ocon', number: 31, team: 'Haas' },
  { firstName: 'Oliver', lastName: 'Bearman', number: 87, team: 'Haas' },
  { firstName: 'Liam', lastName: 'Lawson', number: 30, team: 'Racing Bulls' },
  { firstName: 'Arvid', lastName: 'Lindblad', number: 41, team: 'Racing Bulls' },
  { firstName: 'Carlos', lastName: 'Sainz', number: 55, team: 'Williams' },
  { firstName: 'Alexander', lastName: 'Albon', number: 23, team: 'Williams' },
  { firstName: 'Nico', lastName: 'Hülkenberg', number: 27, team: 'Audi' },
  { firstName: 'Gabriel', lastName: 'Bortoleto', number: 5, team: 'Audi' },
  { firstName: 'Valtteri', lastName: 'Bottas', number: 77, team: 'Cadillac' },
  { firstName: 'Sergio', lastName: 'Pérez', number: 11, team: 'Cadillac' },
]

export const seedRaces: { name: string, location: string, startAt: string }[] = [
  { name: 'Australian Grand Prix', location: 'Melbourne', startAt: '2026-03-08T05:00:00Z' },
  { name: 'Chinese Grand Prix', location: 'Shanghai', startAt: '2026-03-15T07:00:00Z' },
  { name: 'Japanese Grand Prix', location: 'Suzuka', startAt: '2026-03-29T05:00:00Z' },
  { name: 'Bahrain Grand Prix', location: 'Sakhir', startAt: '2026-04-12T15:00:00Z' },
  { name: 'Saudi Arabian Grand Prix', location: 'Jeddah', startAt: '2026-04-19T17:00:00Z' },
  { name: 'Miami Grand Prix', location: 'Miami', startAt: '2026-05-03T20:00:00Z' },
  { name: 'Canadian Grand Prix', location: 'Montreal', startAt: '2026-05-24T18:00:00Z' },
  { name: 'Monaco Grand Prix', location: 'Monaco', startAt: '2026-06-07T13:00:00Z' },
  { name: 'Barcelona-Catalunya Grand Prix', location: 'Barcelona', startAt: '2026-06-14T13:00:00Z' },
  { name: 'Austrian Grand Prix', location: 'Spielberg', startAt: '2026-06-28T13:00:00Z' },
  { name: 'British Grand Prix', location: 'Silverstone', startAt: '2026-07-05T14:00:00Z' },
  { name: 'Belgian Grand Prix', location: 'Spa-Francorchamps', startAt: '2026-07-19T13:00:00Z' },
  { name: 'Hungarian Grand Prix', location: 'Budapest', startAt: '2026-07-26T13:00:00Z' },
  { name: 'Dutch Grand Prix', location: 'Zandvoort', startAt: '2026-08-23T13:00:00Z' },
  { name: 'Italian Grand Prix', location: 'Monza', startAt: '2026-09-06T13:00:00Z' },
  { name: 'Spanish Grand Prix', location: 'Madrid', startAt: '2026-09-13T13:00:00Z' },
  { name: 'Azerbaijan Grand Prix', location: 'Baku', startAt: '2026-09-26T11:00:00Z' },
  { name: 'Singapore Grand Prix', location: 'Singapore', startAt: '2026-10-11T12:00:00Z' },
  { name: 'United States Grand Prix', location: 'Austin', startAt: '2026-10-25T19:00:00Z' },
  { name: 'Mexico City Grand Prix', location: 'Mexico City', startAt: '2026-11-01T20:00:00Z' },
  { name: 'São Paulo Grand Prix', location: 'São Paulo', startAt: '2026-11-08T17:00:00Z' },
  { name: 'Las Vegas Grand Prix', location: 'Las Vegas', startAt: '2026-11-22T06:00:00Z' },
  { name: 'Qatar Grand Prix', location: 'Lusail', startAt: '2026-11-29T14:00:00Z' },
  { name: 'Abu Dhabi Grand Prix', location: 'Abu Dhabi', startAt: '2026-12-06T13:00:00Z' },
]
